# Generated by Django 2.1.2 on 2018-10-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('longitude', models.FloatField()),
                ('latitide', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Login Data',
            },
        ),
    ]
